export const FETCH_ALL_USERS_PENDING = "FETCH_ALL_USERS_PENDING";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED";

export const FETCH_ONE_USER_PENDING = "FETCH_ONE_USER_PENDING";
export const FETCH_ONE_USER_SUCCESS = "FETCH_ONE_USER_SUCCESS";
export const FETCH_ONE_USER_FAILED = "FETCH_ONE_USER_FAILED";

export const ADD_USER_PENDING = "ADD_USER_PENDING";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const REMOVE_USER_PENDING = "REMOVE_USER_PENDING";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILED = "REMOVE_USER_FAILED";

export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const BASE_URL = "http://localhost:8082/api/users";
