export const FETCH_ALL_COMMENTS_PENDING = "FETCH_ALL_COMMENTS_PENDING";
export const FETCH_ALL_COMMENTS_SUCCESS = "FETCH_ALL_COMMENTS_SUCCESS";
export const FETCH_ALL_COMMENTS_FAILED = "FETCH_ALL_COMMENTS_FAILED";

export const FETCH_ONE_COMMENT_PENDING = "FETCH_ONE_COMMENT_PENDING";
export const FETCH_ONE_COMMENT_SUCCESS = "FETCH_ONE_COMMENT_SUCCESS";
export const FETCH_ONE_COMMENT_FAILED = "FETCH_ONE_COMMENT_FAILED";

export const REMOVE_COMMENT_PENDING = "REMOVE_COMMENT_PENDING";
export const REMOVE_COMMENT_SUCCESS = "REMOVE_COMMENT_SUCCESS";
export const REMOVE_COMMENT_FAILED = "REMOVE_COMMENT_FAILED";

export const ADD_COMMENT_PENDING = "ADD_COMMENT_PENDING";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const BASE_URL = `http://localhost:8082/api/sosh/comments`;
