export const FETCH_ALL_STATUSES_PENDING = "FETCH_ALL_STATUSES_PENDING";
export const FETCH_ALL_STATUSES_SUCCESS = "FETCH_ALL_STATUSES_SUCCESS";
export const FETCH_ALL_STATUSES_FAILED = "FETCH_ALL_STATUSES_FAILED";

export const FETCH_ONE_STATUS_PENDING = "FETCH_ONE_STATUS_PENDING";
export const FETCH_ONE_STATUS_SUCCESS = "FETCH_ONE_STATUS_SUCCESS";
export const FETCH_ONE_STATUS_FAILED = "FETCH_ONE_STATUS_FAILED";

export const ADD_STATUS_PENDING = "ADD_STATUS_PENDING";
export const ADD_STATUS_SUCCESS = "ADD_STATUS_SUCCESS";
export const ADD_STATUS_FAILED = "ADD_STATUS_FAILED";

export const REMOVE_STATUS_PENDING = "REMOVE_STATUS_PENDING";
export const REMOVE_STATUS_SUCCESS = "REMOVE_STATUS_SUCCESS";
export const REMOVE_STATUS_FAILED = "REMOVE_STATUS_FAILED";

export const BASE_URL = `http://localhost:8082/api/sosh/statuses`;
