export const FETCH_ALL_FRIENDS_PENDING = "FETCH_ALL_FRIENDS_PENDING";
export const FETCH_ALL_FRIENDS_SUCCESS = "FETCH_ALL_FRIENDS_SUCCESS";
export const FETCH_ALL_FRIENDS_FAILED = "FETCH_ALL_FRIENDS_FAILED";

export const FETCH_ONE_FRIEND_PENDING = "FETCH_ONE_FRIEND_PENDING";
export const FETCH_ONE_FRIEND_SUCCESS = "FETCH_ONE_FRIEND_SUCCESS";
export const FETCH_ONE_FRIEND_FAILED = "FETCH_ONE_FRIEND_FAILED";

export const REMOVE_FRIEND_PENDING = "REMOVE_FRIEND_PENDING";
export const REMOVE_FRIEND_SUCCESS = "REMOVE_FRIEND_SUCCESS";
export const REMOVE_FRIEND_FAILED = "REMOVE_FRIEND_FAILED";

export const ADD_FRIEND_PENDING = "ADD_FRIEND_PENDING";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAILED = "ADD_FRIEND_FAILED";

export const BASE_URL = `http://localhost:8082/api/sosh/friend-requests`;
